name = "lml"
description = "Lightweight Markup Language conversions"
version = "0.1.0-dev"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["markup", "language", "conversion", "json", "yaml", "toml"]

[[actions]]
type = "test"
directory = "test"
command = ["alr", "build"]

[[depends-on]]
ada_toml = "~0.4.0"
gnatcoll = "^21"

[[pins]]
[pins.gnatcoll]
url    = "https://github.com/alire-project/gnatcoll-core.git"
commit = "4e663b87a028252e7e074f054f8f453661397166"
