name = "lml"
description = "Lightweight Markup Language conversions"
version = "0.5.0"
# 0.5.0: internals refactored for better code reuse (common implementations)
# 0.4.0: Schema validation (lml_validate for command-line testing)
# 0.3.0: YAML support (input/output, not anchors)
# 0.2.0: moved to new Alire testsuite

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["markup", "language", "conversion", "json", "yaml", "toml"]

[[actions]]
type = "test"
directory = "test"
command = ["alr", "run"]

[[depends-on]]
ada_toml = "~0.4.0"
json = "^6.0.1"
yamlfk = "~0.2.1"
yeison_12 = "~0.3.1"

[[pins]]

[pins.json]
url    = "https://github.com/mosteo/onox-json-ada"
subdir = "json"
commit = "737296c5e378c33ac823af8404f87ebac0eb2fad"

[pins.yamlfk]
url    = "https://github.com/mosteo/yamlfk"
commit = "460b5b3e33442a4f07554bbf688731f2270002b1"

[pins.yeison_12]
url    = "https://github.com/mosteo/yeison"
subdir = "yeison_12"
commit = "44c648ba48127a3e7d65815f832e64332edeb90f"

[test]
runner = "alire"
