name = "dev"
description = ""
version = "0.1.0-dev"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["dev"]

[build-profiles]
"*" = "validation"

[[depends-on]]
lml = "*"

[[pins]]
lml = { path='..' }

[[pins]]
yeison_12 = { path='../../yeison/yeison_12' }

[[depends-on]]
test = "~0.1.0-dev"

[[pins]]
test = { path='../test' }
