name: build

on:
  push:
    branches: [ master, main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: alire-project/setup-alire@v6
      with:
        version: nightly
        msys2: false # Windows fails otherwise because C: in tar

    - name: Build library
      run: alr build

    - name: Run tests
      run: alr -C test/ run

    # New testsuite

    - name: Run new tests
      run: alr test

